FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5015

ENV ASPNETCORE_URLS=http://+:5015

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["src/WhereIsHong.WebApi/WhereIsHong.WebApi.csproj", "src/WhereIsHong.WebApi/"]
RUN dotnet restore "src/WhereIsHong.WebApi/WhereIsHong.WebApi.csproj"
COPY . .
WORKDIR "/src/src/WhereIsHong.WebApi"
RUN dotnet build "WhereIsHong.WebApi.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "WhereIsHong.WebApi.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WhereIsHong.WebApi.dll"]
